### ISSUE TITLE
Cache SwiftPM dependencies for Github Actions

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/OBAKit#258]
From https://github.com/actions/cache/blob/main/examples.md#swift---swift-package-manager:

```yaml
- uses: actions/cache@v2
  with:
    path: .build
    key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
    restore-keys: |
      ${{ runner.os }}-spm-
```
